server:
  port: 80
  context-path: /cash
#  ssl:
#    key-store: classpath:keystore.p12
#    key-store-type: PKCS12
#    key-alias: tomcat
#    key-store-password: Aa123456!
spring:
  datasource:
    druid:
      write:
        url: jdbc:mysql://localhost:3306/cash?useUnicode=true&characterEncoding=utf-8
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
        initial-size: 4
        max-active: 20
        min-idle: 4
        max-wait: 60000
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        validation-query: select 1 from dual
        test-while-idle: true
        test-on-borrow: true
        test-on-return: true
        pool-prepared-statements: false
        max-pool-prepared-statement-per-connection-size: 20
      read:
        url: jdbc:mysql://localhost:3306/cash?useUnicode=true&characterEncoding=utf-8
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
        initial-size: 4
        max-active: 20
        min-idle: 4
        max-wait: 60000
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        validation-query: select 1 from dual
        test-while-idle: true
        test-on-borrow: true
        test-on-return: true
        pool-prepared-statements: false
        max-pool-prepared-statement-per-connection-size: 20
      #配置初始化大小、最小、最大 -->
      initial-size: 4
      max-active: 20
      min-idle: 4
      #配置获取连接等待超时的时间 -->
      max-wait: 60000
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒 -->
      time-between-eviction-runs-millis: 60000
      #配置一个连接在池中最小生存的时间，单位是毫秒 -->
      min-evictable-idle-time-millis: 300000
      validation-query: select 1 from dual
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
      #配置监控统计拦截的filters
      filter:
        stat:
          #开启慢sql记录功能
          log-slow-sql: true
          slow-sql-millis: 1000
  jackson:
    date-format: yyyy/MM/dd HH:mm:ss
    default-property-inclusion: non_null

  devtools:
    restart:
      #重启排除目录
      exclude: /static/**,/templates/**

  thymeleaf:
    prefix: classpath:/templates
    cache: false
    mode: LEGACYHTML5
  template:
    cache: false

mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.bocs.sys.model


alipay:
  info:
    # 支付宝网关名、partnerId和appId
    openApiDomain: https://openapi.alipaydev.com/gateway.do
    mcloudApiDomain: http://mcloudmonitor.com/gateway.do
    pid: 2088002146781386
    appid: 2016091100488696
    # RSA私钥、公钥和支付宝公钥
    privateKey: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCUiLFMLshPcrzT071Z4/f+OtwWdPa3aWSgpL41fGx73DlFQW7iaIDxtLXLvhUmgt5IH52CtAGvV0nij5XTSrlUwiDtxFsjk46icTj6KKev7LEiJZYuFbDl4WHGjuH8Y+qVcHOBC0H+MJ9dgDsKa9zDUHmL8avN47yCEx9p8axr2TE+8rjvWGG37vtfrfpZIL7Y08xBV8rAbj+I0m1VqtRUgr/Kx6knRHn+3OdG6dCq424G4bDVZZ5Z8KVNsh+t8k1eth9dp3AjUlrWPmwOJllXTXvAPX7dRyw+Xz0aVSRQe/MN+rFe6GEWpew5Bmg5mO2M8UqLhkBIpvBAvE/wq4rRAgMBAAECggEANJ6MONHl8odSL7S2Qs8I/s55Q5diA63ZkTNrkuUmRWbJ/yfkEV82Nupu8OPA+GiqOGDC2xfL9QL2UMXPLRAuwcEYC0NhiiPvBssXhT+70A4I3nD0WBUlGvsSOVZK5q+63f/9WzzSvysYefZAdDur9KFgvdv6ojDIikgd+9k63OWAad0+f6yF3jXmO+R/OodpdWSbTJwXXHmhguqpmDo3isMGdbX1jjL/ZwlIeboj9VxpvlNgO73jPlLdPGUkx/lsb8ZPwuhRZU8eSsQxVwwOtbjP5NaUSb8xe6S7b83ZSq2qKuBXFSY5rUbcPCm/WjFYwACLNFlYEnYpdAXzPOKh9QKBgQD/DRT6+R3H1P3hr8mLt1MpoFmp2J4PQgso2NjlY46fKgZ46KKalvXHYmev6+X1PF5Bw/ztaJm5p4AAoZmh2VQPfjFSlzxteaSPC7vM9CxliymwadOxGk/WdWA7Xsr3iS/zsPA6NlHkgCRXvkcZfxZm55Y/VIgsKii9SWLTsyWrOwKBgQCVFikdUa6BM4lNzNbvO5H5a3C+SXYbl/UW4T0g1szD1jn5Ab3m5mU9dIu3KZaDBDi5xuwlGHcW5d2wLlMHXI92OEI0nouwdw/hXCcUQR2gHAU2Fog5ZdIhJZrA+si3MrpDY/AUaWXLxiU0x/RRGZJh72fdgCK29YyiMtJPTGvJYwKBgQDuElIBKsPnoiMRpTqmVgskke7gIbj4WRd9m1xqUpHwdBPyjIQrdLoa0PokNjhCv4TkMoNHQBouN/G9pRp4/xn+FDcJ9u2K6r72X2d/mnROnKXfbAkUCZF4h7u573PZt46xE/pI/CdY+VvzI0POwtgwWf/fQZKSVxAMEBJVtaV1vQKBgA+ySZngo7LOrkIWsvp1FyVffntKWLkHArLp+/mdI+nqgCgLWucYksgpoRwjsMkShLZqjypIrSEoCnMmLW+0+xXDTpUjrClkH7Pmc+baBDh7OsE7FhSU986tmuF+hetj1+CIgRplDmap8fjgpIR1YMgW4KSdfQouSCQ7nZDjxuVpAoGBAP1lrkuANG/XZEqcQjKv7QC5QeQ1C2/WW04APkQ2lrkE1SSNup0mVXKAG3FXo6+UiQy6pDVDQboPhwnSvQgn6zmMiJXAr0G/o3IZ9c4/5p6CxNTxsssTN8CPFfySKZu9hsFO/pkjBK0nsUU2SctDMk848QBYhXFidLFVnu6HdouC
    publicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAlIixTC7IT3K809O9WeP3/jrcFnT2t2lkoKS+NXxse9w5RUFu4miA8bS1y74VJoLeSB+dgrQBr1dJ4o+V00q5VMIg7cRbI5OOonE4+iinr+yxIiWWLhWw5eFhxo7h/GPqlXBzgQtB/jCfXYA7Cmvcw1B5i/GrzeO8ghMfafGsa9kxPvK471hht+77X636WSC+2NPMQVfKwG4/iNJtVarUVIK/ysepJ0R5/tznRunQquNuBuGw1WWeWfClTbIfrfJNXrYfXadwI1Ja1j5sDiZZV017wD1+3UcsPl89GlUkUHvzDfqxXuhhFqXsOQZoOZjtjPFKi4ZASKbwQLxP8KuK0QIDAQAB
    alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtxpVgMmvW7V4wKc7H0tG0PCvUeFj8FrRclKshuHbMMD5wfreHL9YaItYIc/JgqxeQRhWR745Pn4+b9qaNTBQsEDkMjq4wv2d04pke5iCycNYQmK2h9UQAxdcFV8DhR1Wv6B+cvQP+JztVh27NeWuR7SmNYYQQYTZRnzbVDvL6W2NVYD90TN0z+UAEugQgIxEs80QR4P7aXpjf+K5E3t7rvwz0vWas/yfbo0uZcB4S4BohfEbBQf9zd49G9T7Y7qanDFlph7oCe9pGJvCCrQtU+LEV9/qjd7o9NLa8BB9E/xcYlXAxtF6hEkskADY7gxTV3C8ndbFwmSR3tf4r//SoQIDAQAB