server:
  port: 80
  context-path: /cash
spring:
  datasource:
    druid:
      write:
        url: jdbc:mysql://localhost:3306/cash?useUnicode=true&characterEncoding=utf-8
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
        initial-size: 4
        max-active: 20
        min-idle: 4
        max-wait: 60000
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        validation-query: select 1 from dual
        test-while-idle: true
        test-on-borrow: true
        test-on-return: true
        pool-prepared-statements: false
        max-pool-prepared-statement-per-connection-size: 20
      read:
        url: jdbc:mysql://localhost:3306/cash?useUnicode=true&characterEncoding=utf-8
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
        initial-size: 4
        max-active: 20
        min-idle: 4
        max-wait: 60000
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        validation-query: select 1 from dual
        test-while-idle: true
        test-on-borrow: true
        test-on-return: true
        pool-prepared-statements: false
        max-pool-prepared-statement-per-connection-size: 20
      #配置初始化大小、最小、最大 -->
      initial-size: 4
      max-active: 20
      min-idle: 4
      #配置获取连接等待超时的时间 -->
      max-wait: 60000
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒 -->
      time-between-eviction-runs-millis: 60000
      #配置一个连接在池中最小生存的时间，单位是毫秒 -->
      min-evictable-idle-time-millis: 300000
      validation-query: select 1 from dual
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
      #配置监控统计拦截的filters
      filter:
        stat:
          #开启慢sql记录功能
          log-slow-sql: true
          slow-sql-millis: 1000
  jackson:
    date-format: yyyy/MM/dd HH:mm:ss
    default-property-inclusion: non_null

  devtools:
    restart:
      #重启排除目录
      exclude: /static/**,/templates/**

  thymeleaf:
    prefix: classpath:/templates
    cache: false
    cache-period: 0
  template:
    cache: false

mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.bocs.sys.model

alipay:
  info:
    # 支付宝网关名、partnerId和appId
    openApiDomain: https://openapi.alipay.com/gateway.do
    mcloudApiDomain: http://mcloudmonitor.com/gateway.do
    pid: 2088002146781386
    appid: 2018020202128478
    # RSA私钥、公钥和支付宝公钥
    privateKey: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQChvA0HnTB70TmnBu0MRuoxMZEYuIOs135Br68mAb0OJ4QiQqU+4HRVpTMFJYR+4H30gXN7gMXWDUa59bieHl8j/Y5iERNNb6EHSeQgsRB9P1negf98VuFtPotP5IA2EX0uapYS3wkYsMaV/2wO3JPntG6PohX9n6filXMOALORci4eZ2NNNAQTdJ8FVDKLygAkJ2HR7qc+qZm3ALMMDhqaGSeYgRqH3FxTxOZQUZgH5ZcrgwQcV5j3ck9d0b9+SXBlSikAyuipzODIwgG9lvCUrIP8Vdw9muPtT7F9pOE86aKun+P3c75u6dKsLkkSB0V0yaby1F5lr+athidsjmBBAgMBAAECggEBAIuTbHM7tpHEWErK8Vv8/zMBIcUBx7EsL6ukYDUenvdOJvwiI9WFgyA+dy9j11pfhpOx++WDljhKMNVfN7pNX7IBqhT7w3q6cW+G1zdXV3GfcIFUExZNLDJJHZUPD46ZvTyHg4g5rvH97QOZ8LlKpuH5lsiiCvRcCljCvQ5CkLVdQlMeNthM91ap8QPYlphBROZ0uFVz+sue4uaNcNUjMzjewchPcKrgS7cSdGv1VhUlVuXPP7+JTlZVdSD/ZE4vg/p+5HHfbJXbqPuRIXX3gk2nfICvKjVfMqVWDJ3QfYusxCA7afNiuGlHrl2Q4vaNSKx35uY1TSMetC8j8brgshkCgYEA2neMn+nnSKnlg4pYIvVJ50EAtd7VV8rZbo+iRdt1WDIpedxTjt5qkWZ6gANEjR2fjlJ1bBaBSFLEQy8H/F4KYcUwGMRdaWoXzjLt6wveYQXVeZ4f2zQldsTtcla1pVRCxRw7bB3IZ8aOBbGE2ExxLbMDhHYRF7b50TYvXAFZ17sCgYEAvYVW1Hxr9NEf5++AzEcQX4kUMQ8di76waNUBmnf1aWQUdOXON3iFBJFqGrNNQL/D0ix2rdYNb+v9EhVB3e7K3+eT3yYq94/XHaavGpmZrAFUcjp0WHuwEcTPfDsgP3vdWrYSMBFy3nTd3u8YkYkx5srQoS3CZqU+L0IEsTCD0jMCgYANw5RviswQjuuv4up0oWGbmUPTMYvdcSFLzu7ZWd9FxDtKuy/kg2zRZlR3dj0+asxfqiBNxAk3JkfJN9BX/RDIYiUKmmyMNKv1SM4mjePf1v9BH05AgEOP/Q48suvU0781Lfcsc5/psd/Gyg1ll0NWLr4c/VdMWDHbFX/cWxVu+wKBgQC1raIcVh4DdYnZhH361dD7VGQ3116ifS2NgUxlMMPgwSDfIwF5qZ4ST/fgGqxe+rYUv60RXhZJiXdzo08eGnD/DXdyvpsH8SrtcMGBhWeMPUYfrqujuwaBMiMY23FBilMbR1jOHZv5ZxzePmRV96gPr7MqH7yxO40OLoJi/bgQgwKBgBEwq1NdaqwCn5sRA7eNw9zPo3fYQj+EVvKkX5Yxx3B5fe9Ds9hHgBQKdj+FPh0kL0wkO9j0hRKUBUH+/aB6PVjMKo/GPlTKVOCOeYbVOg9Mfp7DSTB3RTWIlEAdJDnv0OQL5qba1Dmbt7vbYDjoxG5KRhl0QqzOdTarIIOLLML0
    publicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAobwNB50we9E5pwbtDEbqMTGRGLiDrNd+Qa+vJgG9DieEIkKlPuB0VaUzBSWEfuB99IFze4DF1g1GufW4nh5fI/2OYhETTW+hB0nkILEQfT9Z3oH/fFbhbT6LT+SANhF9LmqWEt8JGLDGlf9sDtyT57Ruj6IV/Z+n4pVzDgCzkXIuHmdjTTQEE3SfBVQyi8oAJCdh0e6nPqmZtwCzDA4amhknmIEah9xcU8TmUFGYB+WXK4MEHFeY93JPXdG/fklwZUopAMroqczgyMIBvZbwlKyD/FXcPZrj7U+xfaThPOmirp/j93O+bunSrC5JEgdFdMmm8tReZa/mrYYnbI5gQQIDAQAB
    alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmWKCvKP7hL0QBmI9IwF8iNnWfudRvp04JNoxSOFGMxpGUx/+1l8JQopVPN6H//U9DHANjb6CyujKE4emny77JUIf6XuEjEKcDTnf+E/xpI90IzTeYs8xCoHpEhcFXncdcJZNOOxrjVM/EKTwFhd3lsETLyhNqv+1lWEJd4GlkhvzNhLpvtk0UC8soWj21zCpN8OVIhmSj0SrYL+rCFII0wYK3XRrlbv4CPw2JspdhGNNYd87bBetehzYy1wbaQPwS29Eu9IaLA1TPOiSkLmVUcs2r/Im2T+6JU/jL5plmxy3PIoaQ/uBVPOymCxRKz/Vav6G/7wEytkHNsIiUQxN7wIDAQAB
